### ISSUE TITLE
Update to ConverseJS 10.10.0?

### ISSUE THREAD

**Issue by poVoq** [conversejs/converse-tauri#3]
Would be nice if this was updated to the latest release.

**Comment by licaon-kter** [comment]
At least to 10.1 :)

**Comment by moparisthebest** [comment]
Released the latest https://github.com/conversejs/converse-tauri/releases/tag/v10.1.6

Probably best to ping me on XMPP, I don't notice these normally, sorry about that :(

**Comment by licaon-kter** [comment]
@moparisthebest already did June 16 but whatever...
